import { type Document } from '@/lib/types';

export const documents: Document[] = [
  {
    id_documento: 'doc-001',
    nombre_archivo: 'Q1_Financials_2023.pdf',
    tipo_documento: 'Informe',
    fecha_subida: '2023-03-15T10:00:00Z',
    incidencia: false,
    contenido: 'This is the first quarter financial report for 2023. It includes detailed analysis of revenue streams, operational costs, and profit margins. Key highlights include a 15% increase in year-over-year revenue.',
    ingreso: 120000,
    gasto: 75000,
  },
  {
    id_documento: 'doc-002',
    nombre_archivo: 'Vendor_Contract_ACorp.pdf',
    tipo_documento: 'Contrato',
    fecha_subida: '2023-04-20T14:30:00Z',
    incidencia: false,
    contenido: 'This contract outlines the terms of service between our company and A-Corp. The agreement covers a period of two years, detailing deliverables, payment schedules, and confidentiality clauses.',
    ingreso: 0,
    gasto: 25000,
  },
  {
    id_documento: 'doc-003',
    nombre_archivo: 'INV-2023-05-001.pdf',
    tipo_documento: 'Factura',
    fecha_subida: '2023-05-01T09:00:00Z',
    incidencia: true,
    contenido: 'Invoice for software licensing fees for the month of April. The total amount due is $5,000. Please verify the number of licenses as there might be a discrepancy.',
    ingreso: 0,
    gasto: 5000,
  },
  {
    id_documento: 'doc-004',
    nombre_archivo: 'Marketing_Campaign_Report_Q1.pdf',
    tipo_documento: 'Informe',
    fecha_subida: '2023-04-10T11:20:00Z',
    incidencia: false,
    contenido: 'Analysis of the Q1 marketing campaign performance. The report covers key metrics such as click-through rates, conversion rates, and return on ad spend. Overall, the campaign exceeded targets by 20%.',
    ingreso: 0,
    gasto: 15000,
  },
  {
    id_documento: 'doc-005',
    nombre_archivo: 'Client_Invoice_BSoft.pdf',
    tipo_documento: 'Factura',
    fecha_subida: '2023-05-10T16:45:00Z',
    incidencia: false,
    contenido: 'Invoice sent to B-Soft for consultancy services rendered in April. The total amount is $22,000. Payment is due within 30 days.',
    ingreso: 22000,
    gasto: 0,
  },
  {
    id_documento: 'doc-006',
    nombre_archivo: 'Office_Lease_Agreement.pdf',
    tipo_documento: 'Contrato',
    fecha_subida: '2023-01-05T18:00:00Z',
    incidencia: false,
    contenido: 'The official lease agreement for the new office space at 123 Main Street. The lease term is five years, with an option to renew.',
    ingreso: 0,
    gasto: 12000,
  },
  {
    id_documento: 'doc-007',
    nombre_archivo: 'misc_receipt_01.jpg',
    tipo_documento: 'Otro',
    fecha_subida: '2023-05-18T13:00:00Z',
    incidencia: true,
    contenido: 'This document is a receipt for team lunch. It is a short text and may not be suitable for a summary.',
    ingreso: 0,
    gasto: 350,
  },
    {
    id_documento: 'doc-008',
    nombre_archivo: 'Q2_Sales_Forecast.pdf',
    tipo_documento: 'Informe',
    fecha_subida: '2023-06-01T09:15:00Z',
    incidencia: false,
    contenido: 'The sales forecast for the second quarter of 2023 projects a 10% growth in the enterprise sector. The document details the strategies to achieve this target, including new marketing initiatives and an expanded sales team.',
    ingreso: 150000,
    gasto: 85000,
  },
];
