CREATE TABLE IF NOT EXISTS sugerencias (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  id_usuario BIGINT NOT NULL,
  mensaje TEXT NOT NULL,
  media_urls JSON DEFAULT NULL,
  estado VARCHAR(50) DEFAULT 'pendiente',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
