// This file was generated by prisma-field-encryption.

import type { PrismaClient, archivos_documento } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = archivos_documento['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'archivos_documento',
    client,
    getTotalCount: client.archivos_documento.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.archivos_documento.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        nombre_archivo: true,
        ruta_archivo: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.archivos_documento.update({
      where: {
        id: record.id
      },
      data: {
        nombre_archivo: record.nombre_archivo,
        ruta_archivo: record.ruta_archivo
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "nombre_archivo": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "ruta_archivo": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "documentos": {
 *       "modelName": "documentos",
 *       "isList": false
 *     },
 *     "empresas": {
 *       "modelName": "empresas",
 *       "isList": false
 *     }
 *   }
 * }
 */
