// This file was generated by prisma-field-encryption.

import type { PrismaClient, empresas } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = empresas['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'empresas',
    client,
    getTotalCount: client.empresas.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.empresas.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        nombre_de_empresa: true,
        nombre_fiscal: true,
        mail_de_carga: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.empresas.update({
      where: {
        id: record.id
      },
      data: {
        nombre_de_empresa: record.nombre_de_empresa,
        nombre_fiscal: record.nombre_fiscal,
        mail_de_carga: record.mail_de_carga
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "nombre_de_empresa": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "nombre_fiscal": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "mail_de_carga": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "actividad": {
 *       "modelName": "actividad",
 *       "isList": true
 *     },
 *     "archivos_documento": {
 *       "modelName": "archivos_documento",
 *       "isList": true
 *     },
 *     "documentos": {
 *       "modelName": "documentos",
 *       "isList": true
 *     },
 *     "documentos_auditoria": {
 *       "modelName": "documentos_auditoria",
 *       "isList": true
 *     },
 *     "entidades_config": {
 *       "modelName": "entidades_config",
 *       "isList": true
 *     },
 *     "entidades_documento": {
 *       "modelName": "entidades_documento",
 *       "isList": true
 *     },
 *     "impuestos_documento": {
 *       "modelName": "impuestos_documento",
 *       "isList": true
 *     },
 *     "incidencias_documento": {
 *       "modelName": "incidencias_documento",
 *       "isList": true
 *     },
 *     "lineas_documento": {
 *       "modelName": "lineas_documento",
 *       "isList": true
 *     },
 *     "trimestres": {
 *       "modelName": "trimestres",
 *       "isList": true
 *     },
 *     "usuarios": {
 *       "modelName": "usuarios",
 *       "isList": true
 *     },
 *     "webhooks_empresa": {
 *       "modelName": "webhooks_empresa",
 *       "isList": true
 *     }
 *   }
 * }
 */
