// This file was generated by prisma-field-encryption.

import type { PrismaClient, entidades_config } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = entidades_config['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'entidades_config',
    client,
    getTotalCount: client.entidades_config.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.entidades_config.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        identificador_fiscal: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.entidades_config.update({
      where: {
        id: record.id
      },
      data: {
        identificador_fiscal: record.identificador_fiscal
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "identificador_fiscal": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "empresas": {
 *       "modelName": "empresas",
 *       "isList": false
 *     }
 *   }
 * }
 */
