// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '@prisma/client'
import { migrate as migrateusuarios } from './usuarios'
import { migrate as migrateempresas } from './empresas'
import { migrate as migrateentidades_documento } from './entidades_documento'
import { migrate as migrateinvitaciones_empresa } from './invitaciones_empresa'
import { migrate as migratearchivos_documento } from './archivos_documento'
import { migrate as migrateentidades_config } from './entidades_config'
import { migrate as migrateproductos_config } from './productos_config'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(20)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  usuarios: number,
  empresas: number,
  entidades_documento: number,
  invitaciones_empresa: number,
  archivos_documento: number,
  entidades_config: number,
  productos_config: number
}

/**
 * Migrate models sequentially.
 *
 * Processed models:
 * - usuarios
 * - empresas
 * - entidades_documento
 * - invitaciones_empresa
 * - archivos_documento
 * - entidades_config
 * - productos_config
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const processedusuarios = await migrateusuarios(client, reportProgress)
  const processedempresas = await migrateempresas(client, reportProgress)
  const processedentidades_documento = await migrateentidades_documento(client, reportProgress)
  const processedinvitaciones_empresa = await migrateinvitaciones_empresa(client, reportProgress)
  const processedarchivos_documento = await migratearchivos_documento(client, reportProgress)
  const processedentidades_config = await migrateentidades_config(client, reportProgress)
  const processedproductos_config = await migrateproductos_config(client, reportProgress)
  return {
    usuarios: processedusuarios,
    empresas: processedempresas,
    entidades_documento: processedentidades_documento,
    invitaciones_empresa: processedinvitaciones_empresa,
    archivos_documento: processedarchivos_documento,
    entidades_config: processedentidades_config,
    productos_config: processedproductos_config
  }
}
