// This file was generated by prisma-field-encryption.

import type { PrismaClient, usuarios } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = usuarios['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'usuarios',
    client,
    getTotalCount: client.usuarios.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.usuarios.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        nombre: true,
        email: true,
        phone: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.usuarios.update({
      where: {
        id: record.id
      },
      data: {
        nombre: record.nombre,
        email: record.email,
        phone: record.phone
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "nombre": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "email": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "phone": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "ai_daily_usage": {
 *       "modelName": "ai_daily_usage",
 *       "isList": true
 *     },
 *     "ai_usage_log": {
 *       "modelName": "ai_usage_log",
 *       "isList": true
 *     },
 *     "ai_user_config": {
 *       "modelName": "ai_user_config",
 *       "isList": false
 *     },
 *     "exports": {
 *       "modelName": "exports",
 *       "isList": true
 *     },
 *     "incidencias_documento": {
 *       "modelName": "incidencias_documento",
 *       "isList": true
 *     },
 *     "password_reset_tokens": {
 *       "modelName": "password_reset_tokens",
 *       "isList": true
 *     },
 *     "empresas": {
 *       "modelName": "empresas",
 *       "isList": false
 *     }
 *   }
 * }
 */
